swagger_docs:
  '1.0.0':
    info:
      title: Bitcoin API
      description: API para consultar el precio del BTC en tiempo real y realizar transacciones de compra o venta
      version: 1.0.0
    host: localhost:3000
    basePath: /
    schemes:
      - http
    consumes:
      - application/json
    produces:
      - application/json
    paths:
      /price:
        get:
          summary: Obtener el precio del BTC en tiempo real
          operationId: getPrice
          responses:
            200:
              description: El precio del BTC en tiempo real
              schema:
                type: object
                properties:
                  price:
                    type: number
                    format: float
                    example: 50000.00
      /users:
        post:
          summary: Crear un nuevo usuario
          operationId: createUser
          parameters:
            - in: body
              name: body
              description: Datos del usuario
              required: true
              schema:
                type: object
                properties:
                  name:
                    type: string
                  balance_usd:
                    type: number
                    format: float
                    example: 1000.00
                  balance_btc:
                    type: number
                    format: float
                    example: 0.0002
          responses:
            201:
              description: Usuario creado exitosamente
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  name:
                    type: string
                    example: John Doe
                  balance_usd:
                    type: number
                    format: float
                    example: 1000.00
                  balance_btc:
                    type: number
                    format: float
                    example: 0.0002
      /users/{id}/transactions:
        get:
          summary: Obtener las transacciones de un usuario
          operationId: getTransactionsByUser
          parameters:
            - in: path
              name: id
              description: ID del usuario
              required: true
              schema:
                type: integer
                format: int64
                minimum: 1
          responses:
            200:
              description: Lista de transacciones del usuario
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
      /transactions:
        post:
          summary: Realizar una transacción de compra o venta
          operationId: createTransaction
          parameters:
            - in: body
              name: body
                           description: Datos de la transacción
             required: true
             schema:
               type: object
               properties:
                 user_id:
                   type: integer
                   format: int64
                   example: 1
                 transaction:
                   type: object
                   properties:
                     coin_sent:
                       type: string
                       example: USD
                     coin_received:
                       type: string
                       example: BTC
                     amount_sent:
                       type: number
                       format: float
                       example: 100.00
                     amount_received:
                       type: number
                       format: float
                       example: 0.0002
         responses:
           201:
             description: Transacción creada exitosamente
             schema:
               type: object
               properties:
                 id:
                   type: integer
                   format: int64
                   example: 1
                 user_id:
                   type: integer
                   format: int64
                   example: 1
                 coin_sent:
                   type: string
                   example: USD
                 coin_received:
                   type: string
                   example: BTC
                 amount_sent:
                   type: number
                   format: float
                   example: 100.00
                 amount_received:
                   type: number
                   format: float
                   example: 0.0002
     /transactions/{id}:
       get:
         summary: Obtener una transacción específica
         operationId: getTransaction
         parameters:
           - in: path
             name: id
             description: ID de la transacción
             required: true
             schema:
               type: integer
               format: int64
               minimum: 1
         responses:
           200:
             description: Detalles de la transacción
             schema:
               type: object
               properties:
                 id:
                   type: integer
                   format: int64
                   example: 1
                 user_id:
                   type: integer
                   format: int64
                   example: 1
                 coin_sent:
                   type: string
                   example: USD
                 coin_received:
                   type: string
                   example: BTC
                 amount_sent:
                   type: number
                   format: float
                   example: 100.00
                 amount_received:
                   type: number
                   format: float
                   example: 0.0002